/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef CRAY1
#ifndef inline_t 
#define inline_t long
#endif /* !inline_t */
#endif /* !CRAY1 */

#include "rstat.h"
/*
 * Copyright (c) 1985, 1990, 1991 by Sun Microsystems, Inc.
 */
/* from rstat.x */
/*
 * XDR routines for the rstat daemon, rup and perfmeter.
 */

/*
 * xdr_timeval was used in previous releases.
 */

bool_t
#ifdef __STDC__
xdr_timeval(XDR *xdrs, struct timeval *tvp)
#else /* K&R C */
xdr_timeval(xdrs, tvp)
	XDR *xdrs;
	struct timeval *tvp;
#endif /* K&R C */
{
	return (xdr_rstat_timeval(xdrs, tvp));
}


bool_t
xdr_rstat_timeval(xdrs, objp)
	register XDR *xdrs;
	rstat_timeval *objp;
{

	register inline_t *buf;

	if (!xdr_long(xdrs, &objp->tv_sec))
		return (FALSE);
	if (!xdr_long(xdrs, &objp->tv_usec))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_statsvar(xdrs, objp)
	register XDR *xdrs;
	statsvar *objp;
{

	register inline_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		if (!xdr_array(xdrs, (char **)&objp->cp_time.cp_time_val, (u_int *) &objp->cp_time.cp_time_len, ~0,
			sizeof (int), (xdrproc_t) xdr_int))
			return (FALSE);
		if (!xdr_array(xdrs, (char **)&objp->dk_xfer.dk_xfer_val, (u_int *) &objp->dk_xfer.dk_xfer_len, ~0,
			sizeof (int), (xdrproc_t) xdr_int))
			return (FALSE);

		buf = XDR_INLINE(xdrs, (11 + 3) * BYTES_PER_XDR_UNIT);

		if (buf == NULL) {
			if (!xdr_u_int(xdrs, &objp->v_pgpgin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_intr))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ipackets))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ierrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_opackets))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_oerrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_collisions))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_swtch))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->avenrun, 3,
				sizeof (long), (xdrproc_t) xdr_long))
				return (FALSE);

		} else {
			IXDR_PUT_U_LONG(buf, objp->v_pgpgin);
			IXDR_PUT_U_LONG(buf, objp->v_pgpgout);
			IXDR_PUT_U_LONG(buf, objp->v_pswpin);
			IXDR_PUT_U_LONG(buf, objp->v_pswpout);
			IXDR_PUT_U_LONG(buf, objp->v_intr);
			IXDR_PUT_LONG(buf, objp->if_ipackets);
			IXDR_PUT_LONG(buf, objp->if_ierrors);
			IXDR_PUT_LONG(buf, objp->if_opackets);
			IXDR_PUT_LONG(buf, objp->if_oerrors);
			IXDR_PUT_LONG(buf, objp->if_collisions);
			IXDR_PUT_U_LONG(buf, objp->v_swtch);
			{
				register long *genp;

				for (i = 0, genp = objp->avenrun;
					i < 3; i++) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		if (!xdr_rstat_timeval(xdrs, &objp->boottime))
			return (FALSE);
		if (!xdr_rstat_timeval(xdrs, &objp->curtime))
			return (FALSE);
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		if (!xdr_array(xdrs, (char **)&objp->cp_time.cp_time_val, (u_int *) &objp->cp_time.cp_time_len, ~0,
			sizeof (int), (xdrproc_t) xdr_int))
			return (FALSE);
		if (!xdr_array(xdrs, (char **)&objp->dk_xfer.dk_xfer_val, (u_int *) &objp->dk_xfer.dk_xfer_len, ~0,
			sizeof (int), (xdrproc_t) xdr_int))
			return (FALSE);

		buf = XDR_INLINE(xdrs, (11 + 3) * BYTES_PER_XDR_UNIT);

		if (buf == NULL) {
			if (!xdr_u_int(xdrs, &objp->v_pgpgin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_intr))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ipackets))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ierrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_opackets))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_oerrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_collisions))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_swtch))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->avenrun, 3,
				sizeof (long), (xdrproc_t) xdr_long))
				return (FALSE);

		} else {
			objp->v_pgpgin = IXDR_GET_U_LONG(buf);
			objp->v_pgpgout = IXDR_GET_U_LONG(buf);
			objp->v_pswpin = IXDR_GET_U_LONG(buf);
			objp->v_pswpout = IXDR_GET_U_LONG(buf);
			objp->v_intr = IXDR_GET_U_LONG(buf);
			objp->if_ipackets = IXDR_GET_LONG(buf);
			objp->if_ierrors = IXDR_GET_LONG(buf);
			objp->if_opackets = IXDR_GET_LONG(buf);
			objp->if_oerrors = IXDR_GET_LONG(buf);
			objp->if_collisions = IXDR_GET_LONG(buf);
			objp->v_swtch = IXDR_GET_U_LONG(buf);
			{
				register long *genp;

				for (i = 0, genp = objp->avenrun;
					i < 3; i++) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
		if (!xdr_rstat_timeval(xdrs, &objp->boottime))
			return (FALSE);
		if (!xdr_rstat_timeval(xdrs, &objp->curtime))
			return (FALSE);
		return (TRUE);
	}

	if (!xdr_array(xdrs, (char **)&objp->cp_time.cp_time_val, (u_int *) &objp->cp_time.cp_time_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->dk_xfer.dk_xfer_val, (u_int *) &objp->dk_xfer.dk_xfer_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pgpgin))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pgpgout))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pswpin))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pswpout))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_intr))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_ipackets))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_ierrors))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_opackets))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_oerrors))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_collisions))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_swtch))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->avenrun, 3,
		sizeof (long), (xdrproc_t) xdr_long))
		return (FALSE);
	if (!xdr_rstat_timeval(xdrs, &objp->boottime))
		return (FALSE);
	if (!xdr_rstat_timeval(xdrs, &objp->curtime))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_statstime(xdrs, objp)
	register XDR *xdrs;
	statstime *objp;
{

	register inline_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE(xdrs, (10 + (RSTAT_CPUSTATES + RSTAT_DK_NDRIVE + 3)) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_vector(xdrs, (char *)objp->cp_time, RSTAT_CPUSTATES,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->dk_xfer, RSTAT_DK_NDRIVE,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_intr))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ipackets))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ierrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_oerrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_collisions))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_swtch))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->avenrun, 3,
				sizeof (long), (xdrproc_t) xdr_long))
				return (FALSE);

		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->cp_time;
					i < RSTAT_CPUSTATES; i++) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->dk_xfer;
					i < RSTAT_DK_NDRIVE; i++) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_U_LONG(buf, objp->v_pgpgin);
			IXDR_PUT_U_LONG(buf, objp->v_pgpgout);
			IXDR_PUT_U_LONG(buf, objp->v_pswpin);
			IXDR_PUT_U_LONG(buf, objp->v_pswpout);
			IXDR_PUT_U_LONG(buf, objp->v_intr);
			IXDR_PUT_LONG(buf, objp->if_ipackets);
			IXDR_PUT_LONG(buf, objp->if_ierrors);
			IXDR_PUT_LONG(buf, objp->if_oerrors);
			IXDR_PUT_LONG(buf, objp->if_collisions);
			IXDR_PUT_U_LONG(buf, objp->v_swtch);
			{
				register long *genp;

				for (i = 0, genp = objp->avenrun;
					i < 3; i++) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		if (!xdr_rstat_timeval(xdrs, &objp->boottime))
			return (FALSE);
		if (!xdr_rstat_timeval(xdrs, &objp->curtime))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->if_opackets))
			return (FALSE);
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE(xdrs, (10 + (RSTAT_CPUSTATES + RSTAT_DK_NDRIVE + 3)) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_vector(xdrs, (char *)objp->cp_time, RSTAT_CPUSTATES,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->dk_xfer, RSTAT_DK_NDRIVE,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_intr))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ipackets))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ierrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_oerrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_collisions))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_swtch))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->avenrun, 3,
				sizeof (long), (xdrproc_t) xdr_long))
				return (FALSE);

		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->cp_time;
					i < RSTAT_CPUSTATES; i++) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->dk_xfer;
					i < RSTAT_DK_NDRIVE; i++) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->v_pgpgin = IXDR_GET_U_LONG(buf);
			objp->v_pgpgout = IXDR_GET_U_LONG(buf);
			objp->v_pswpin = IXDR_GET_U_LONG(buf);
			objp->v_pswpout = IXDR_GET_U_LONG(buf);
			objp->v_intr = IXDR_GET_U_LONG(buf);
			objp->if_ipackets = IXDR_GET_LONG(buf);
			objp->if_ierrors = IXDR_GET_LONG(buf);
			objp->if_oerrors = IXDR_GET_LONG(buf);
			objp->if_collisions = IXDR_GET_LONG(buf);
			objp->v_swtch = IXDR_GET_U_LONG(buf);
			{
				register long *genp;

				for (i = 0, genp = objp->avenrun;
					i < 3; i++) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
		if (!xdr_rstat_timeval(xdrs, &objp->boottime))
			return (FALSE);
		if (!xdr_rstat_timeval(xdrs, &objp->curtime))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->if_opackets))
			return (FALSE);
		return (TRUE);
	}

	if (!xdr_vector(xdrs, (char *)objp->cp_time, RSTAT_CPUSTATES,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->dk_xfer, RSTAT_DK_NDRIVE,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pgpgin))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pgpgout))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pswpin))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pswpout))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_intr))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_ipackets))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_ierrors))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_oerrors))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_collisions))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_swtch))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->avenrun, 3,
		sizeof (long), (xdrproc_t) xdr_long))
		return (FALSE);
	if (!xdr_rstat_timeval(xdrs, &objp->boottime))
		return (FALSE);
	if (!xdr_rstat_timeval(xdrs, &objp->curtime))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_opackets))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_statsswtch(xdrs, objp)
	register XDR *xdrs;
	statsswtch *objp;
{

	register inline_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE(xdrs, (10 + (RSTAT_CPUSTATES + RSTAT_DK_NDRIVE + 3)) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_vector(xdrs, (char *)objp->cp_time, RSTAT_CPUSTATES,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->dk_xfer, RSTAT_DK_NDRIVE,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_intr))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ipackets))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ierrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_oerrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_collisions))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_swtch))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->avenrun, 3,
				sizeof (u_int), (xdrproc_t) xdr_u_int))
				return (FALSE);

		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->cp_time;
					i < RSTAT_CPUSTATES; i++) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->dk_xfer;
					i < RSTAT_DK_NDRIVE; i++) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_U_LONG(buf, objp->v_pgpgin);
			IXDR_PUT_U_LONG(buf, objp->v_pgpgout);
			IXDR_PUT_U_LONG(buf, objp->v_pswpin);
			IXDR_PUT_U_LONG(buf, objp->v_pswpout);
			IXDR_PUT_U_LONG(buf, objp->v_intr);
			IXDR_PUT_LONG(buf, objp->if_ipackets);
			IXDR_PUT_LONG(buf, objp->if_ierrors);
			IXDR_PUT_LONG(buf, objp->if_oerrors);
			IXDR_PUT_LONG(buf, objp->if_collisions);
			IXDR_PUT_U_LONG(buf, objp->v_swtch);
			{
				register u_int *genp;

				for (i = 0, genp = objp->avenrun;
					i < 3; i++) {
					IXDR_PUT_U_LONG(buf, *genp++);
				}
			}
		}
		if (!xdr_rstat_timeval(xdrs, &objp->boottime))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->if_opackets))
			return (FALSE);
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE(xdrs, (10 + (RSTAT_CPUSTATES + RSTAT_DK_NDRIVE + 3)) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_vector(xdrs, (char *)objp->cp_time, RSTAT_CPUSTATES,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->dk_xfer, RSTAT_DK_NDRIVE,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_intr))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ipackets))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ierrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_oerrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_collisions))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_swtch))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->avenrun, 3,
				sizeof (u_int), (xdrproc_t) xdr_u_int))
				return (FALSE);

		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->cp_time;
					i < RSTAT_CPUSTATES; i++) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->dk_xfer;
					i < RSTAT_DK_NDRIVE; i++) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->v_pgpgin = IXDR_GET_U_LONG(buf);
			objp->v_pgpgout = IXDR_GET_U_LONG(buf);
			objp->v_pswpin = IXDR_GET_U_LONG(buf);
			objp->v_pswpout = IXDR_GET_U_LONG(buf);
			objp->v_intr = IXDR_GET_U_LONG(buf);
			objp->if_ipackets = IXDR_GET_LONG(buf);
			objp->if_ierrors = IXDR_GET_LONG(buf);
			objp->if_oerrors = IXDR_GET_LONG(buf);
			objp->if_collisions = IXDR_GET_LONG(buf);
			objp->v_swtch = IXDR_GET_U_LONG(buf);
			{
				register u_int *genp;

				for (i = 0, genp = objp->avenrun;
					i < 3; i++) {
					*genp++ = IXDR_GET_U_LONG(buf);
				}
			}
		}
		if (!xdr_rstat_timeval(xdrs, &objp->boottime))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->if_opackets))
			return (FALSE);
		return (TRUE);
	}

	if (!xdr_vector(xdrs, (char *)objp->cp_time, RSTAT_CPUSTATES,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->dk_xfer, RSTAT_DK_NDRIVE,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pgpgin))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pgpgout))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pswpin))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pswpout))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_intr))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_ipackets))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_ierrors))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_oerrors))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_collisions))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_swtch))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->avenrun, 3,
		sizeof (u_int), (xdrproc_t) xdr_u_int))
		return (FALSE);
	if (!xdr_rstat_timeval(xdrs, &objp->boottime))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_opackets))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_stats(xdrs, objp)
	register XDR *xdrs;
	stats *objp;
{

	register inline_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE(xdrs, (10 + (RSTAT_CPUSTATES + RSTAT_DK_NDRIVE)) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_vector(xdrs, (char *)objp->cp_time, RSTAT_CPUSTATES,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->dk_xfer, RSTAT_DK_NDRIVE,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_intr))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ipackets))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ierrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_oerrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_collisions))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_opackets))
				return (FALSE);
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->cp_time;
					i < RSTAT_CPUSTATES; i++) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->dk_xfer;
					i < RSTAT_DK_NDRIVE; i++) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_U_LONG(buf, objp->v_pgpgin);
			IXDR_PUT_U_LONG(buf, objp->v_pgpgout);
			IXDR_PUT_U_LONG(buf, objp->v_pswpin);
			IXDR_PUT_U_LONG(buf, objp->v_pswpout);
			IXDR_PUT_U_LONG(buf, objp->v_intr);
			IXDR_PUT_LONG(buf, objp->if_ipackets);
			IXDR_PUT_LONG(buf, objp->if_ierrors);
			IXDR_PUT_LONG(buf, objp->if_oerrors);
			IXDR_PUT_LONG(buf, objp->if_collisions);
			IXDR_PUT_LONG(buf, objp->if_opackets);
		}
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE(xdrs, (10 + (RSTAT_CPUSTATES + RSTAT_DK_NDRIVE)) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_vector(xdrs, (char *)objp->cp_time, RSTAT_CPUSTATES,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->dk_xfer, RSTAT_DK_NDRIVE,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pgpgout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpin))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_pswpout))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->v_intr))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ipackets))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_ierrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_oerrors))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_collisions))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->if_opackets))
				return (FALSE);
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->cp_time;
					i < RSTAT_CPUSTATES; i++) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->dk_xfer;
					i < RSTAT_DK_NDRIVE; i++) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->v_pgpgin = IXDR_GET_U_LONG(buf);
			objp->v_pgpgout = IXDR_GET_U_LONG(buf);
			objp->v_pswpin = IXDR_GET_U_LONG(buf);
			objp->v_pswpout = IXDR_GET_U_LONG(buf);
			objp->v_intr = IXDR_GET_U_LONG(buf);
			objp->if_ipackets = IXDR_GET_LONG(buf);
			objp->if_ierrors = IXDR_GET_LONG(buf);
			objp->if_oerrors = IXDR_GET_LONG(buf);
			objp->if_collisions = IXDR_GET_LONG(buf);
			objp->if_opackets = IXDR_GET_LONG(buf);
		}
		return (TRUE);
	}

	if (!xdr_vector(xdrs, (char *)objp->cp_time, RSTAT_CPUSTATES,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->dk_xfer, RSTAT_DK_NDRIVE,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pgpgin))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pgpgout))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pswpin))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_pswpout))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->v_intr))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_ipackets))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_ierrors))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_oerrors))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_collisions))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->if_opackets))
		return (FALSE);
	return (TRUE);
}
